version: '3.8'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=minhasenha
      - MYSQL_DATABASE=CSAT
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "9229:9229"
    # command: sh -c "npm install && sleep 10 && node src/server.js"

    command: sh -c "npm install && sleep 10 && node --inspect=0.0.0.0:9229 src/server.js"

    env_file:
      - .env
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
